### ISSUE TITLE
Checklist for initial release

### ISSUE THREAD

**Issue by mjlbach** [neovim/packspec#15]
- [x] write some guidance for required/optional features of implementers
- [x]  Settle on name `packagespec`, `plugspec` and updated the `package_specification` field and the documentation
- [x]  Provide a section on plugin expectations? (Semver, vimdoc, etc.)
- [ ] Address concern about dependencies format (including neovim as a dependency) https://github.com/nvim-lua/nvim-package-specification/issues/19
- [ ] Add build steps for plugins https://github.com/nvim-lua/nvim-package-specification/issues/23
- [ ] Upload final version of json schema to schema store

**Comment by ii14** [comment]
If there is a new name, maybe `plugin.{lua,json}` should be changed to `plugspec.{lua,json}` too?

**Comment by mjlbach** [comment]
I'm still not sold on`plug`, this spec can apply to libraries as well, and also still has `vim-plug` connotations.

**Comment by lewis6991** [comment]
Go with `packspec` then?

**Comment by lewis6991** [comment]
> Consider moving neovim out of external dependencies to it's own versioned key

I lean against doing this. We could maybe add a general `requirements` field but that would pretty much only contain Neovim.

**Comment by mjlbach** [comment]
Yeah, just wanted to put it as it came up on the neovim general chat by shougo :)

**Comment by lewis6991** [comment]
I've changed my mind on this and think we should pull it out.

**Comment by mjlbach** [comment]
Are you thinking more like https://github.com/nvim-lua/nvim-package-specification/issues/19 initially proposed (as an independent field in dependencies or more top level?

**Comment by lewis6991** [comment]
Yeah pretty much. I also think we need to change dependencies as per that ticket.
